AimTuxOfficial/AimTux

src/UI/strptextbox.h
src/UI/textbox.h
src/WINDOWS/misc_window.cpp
src/WINDOWS/misc_window.h
src/chantagchanger.cpp
src/settings.cpp
src/settings.h
src/util.cpp
src/util.h

Also: 
* adds a toggle for clantag changer (half working - doesn't revert to actual clan tag)
*  move `\n => <newline>` replacement to send-time so that it's not saved/does not modify the actual settings value
* change type of `Settings::ClanTagChanger::value` to `std::string` from char array.
* Correct `GetString` logic to actually update string contents
* Add a search/replace algo to `Util` that operates on `std::string`.

Fix #27: Re-load clantag from settings; make TextBox use string pointer instead of value

---

_local_vimrc.vim

This should make sure anyone with `local_vimrc` installed (myself included) uses tabs by default.

Add local vimrc

---

src/vmt.h

Line 35: Virtual was misspelled.

Misspelling in comment in vmt.h

---

src/AimTux.cpp
src/SDK/IGameMovement.h
src/SDK/IPrediction.h
src/SDK/SDK.h
src/hooker.cpp
src/hooker.h
src/interfaces.h

Played around with this in another project and it works well. I tried adding it in CreateMove here but it seemed to interfere with some other features so this covers everything but the actual implementation.
I've uploaded example usage for CreateMove [here](https://gist.github.com/aixxe/65580e54d3d759130a7882c6ee19eef4) based on the [engine prediction](https://www.unknowncheats.me/forum/counterstrike-global-offensive/189474-engine-prediction.html) code from UnKnoWnCheaTs. It's easiest to test this with `weapon_accuracy_nospread` set to 1 and recoil control in AimTux set to 2.

Add base classes and signatures for engine prediction.

---

src/settings.cpp
src/util_input.cpp
src/util_input.h

This change ultimately replaces the use of numeric key codes in the configuration files.
It adds two functions in the namespace `Util::Input` that allow looking up button codes and names by each other respectively.
When saving configuration files, button codes will now be saved as their symbolic counterpart, e.g. `"KEY_LCONTROL"` as opposed to `83`.
When loading configuration files, either a numeric value or a symbolic value will be accepted, but when saving only the symbolic value will be written - thus converting old configuration files.

Add support for using symbolic button names in the configuration files

---

src/settings.cpp
src/util.cpp
src/util.h
src/util_input.cpp
src/util_input.h

Also moves the map reverse and forward defaulting search logic in to `util.h` as two template functions. 
I tested this at 2 AM and it should be working.

Add symbolic ordinal support for skin changer

---

src/Hooks/FrameStageNotify.cpp
src/SDK/CGlowObjectManager.h
src/SDK/CUtlMemory.h
src/SDK/CUtlVector.h
src/SDK/IClientEntity.h
src/SDK/SDK.h
src/SDK/definitions.h
src/customglow.cpp
src/customglow.h
src/esp.cpp
src/esp.h
src/hacks.h
src/hooker.cpp
src/interfaces.h
src/offsets.cpp
src/offsets.h
src/settings.cpp
src/settings.h

As requested in #158, this will apply a glow effect to dropped defuser kit entities while playing on the CT side without a kit. If there are too many entities already in the glow definition list it won't grow the vector, as this [doesn't seem to make any difference](https://www.unknowncheats.me/forum/1588459-post6.html).
I've replaced the existing glow manager class with a proper CUtlVector and CUtlMemory implementation just in case some progress is made further down the line in that area.
The defuser check is a simple class comparison for CBaseAnimating. This should be fine on official servers but might cause some issues on community servers if they use custom entities with this class.
I had some issues with crashing when calling CustomGlow during `FRAME_RENDER_START` only, I can't …

Add ability to apply glow to custom entities.

---

src/AimTux.cpp
src/SDK/common.h
src/interfaces.cpp
src/interfaces.h

- GetInterface will now check for nullptr before casting
- Implement interface dumping (dumps to game_root/interface.txt)

GetInterface fixes and interface dumping

---

src/aimbot.cpp
src/triggerbot.cpp

- Replace cmd->viewangles with engine->GetViewAngles for both aimbot and triggerbot
This should improve reliability of both aimbot and triggerbot, since mouse input (and thus viewangles) are sampled more times than usercmds are.

Improve aimbot & triggerbot

---

src/atgui.cpp
src/esp.cpp
src/esp.h
src/settings.cpp
src/settings.h

- Move NoScopeBorder out of experimental settings since it's finally usable
- Draw custom scope crosshair like in b1g p2cs

Finish NoScopeBorder

---

src/Hooks/BeginFrame.cpp
src/entity.cpp
src/entity.h
src/esp.cpp
src/radar.cpp
src/radar.h

- Calling IEngineTrace::TraceRay outside game's threads causes crashes, move visibility checks to BeginFrame
- Triangles used in radar were too small compared to circles and squares
- Use proper border checks in WorldToRadar
- Remove useless and broken code from ESP::GetESPPlayerColor
- Change the way immune-color is computed
- Add fov parameter to Entity::IsVisible so that it can check whether player is visible within given field of view

Improved radar and various fixes

---

src/Hooks/CreateMove.cpp
src/atgui.cpp
src/autoblock.cpp
src/autoblock.h
src/hacks.h
src/settings.cpp
src/settings.h

An autoblock (sometimes referred to as a blocker or an autoblocker) can be used to block teammates. This works by mirroring your target's moves while facing them, so that they can not get past you. This can be useful for griefing teammates by trapping them in spawn if they are being annoying.
I have implemented the feature itself, and I have added it to the GUI in the miscellaneous section. The default keybind for it is 6 (this should really be changed to a different key - I have temporarily chosen this one because I know it's not used for anything else).
[Here](https://www.youtube.com/watch?v=Tvzz9qGLh-0) is a link to a similar autoblock in action.

Added autoblock

---

src/SDK/vector.h
src/autoblock.cpp
src/esp.cpp

So for 3D vectors AimTux currently does not have a vector distance function (?), only a vector distance squared function, so I have implemented a normal function to save some worthless calculations. If you just look at the code you can see that it is inefficient, as the code is finding a number squared and then square rooting it.

Improve efficiency (muh CPU cycles)

---

src/AimTux.cpp
src/Hacks/fovchanger.cpp
src/Hacks/hacks.h
src/Hacks/nosmoke.cpp
src/Hacks/nosmoke.h
src/Hooks/FrameStageNotify.cpp
src/Hooks/RenderView.cpp
src/Hooks/hooks.h
src/SDK/IMaterial.h
src/atgui.cpp
src/hooker.cpp
src/settings.cpp
src/settings.h

- Disables smoke overlay and forces world rendering while in smoke via RenderSmokePreViewmodel hook
- Disables smoke rendering by setting MATERIAL_VAR_NO_DRAW on smoke's materials

Implement No Smoke & Fix Ignore Scope

---

src/atgui.cpp

it teleports on 0,0,your current z, not 0,0,0

teleport gui fix

---

src/Hacks/autostrafe.cpp
src/atgui.cpp
src/settings.cpp
src/settings.h

Original author: Roskonix
- Implement 'silent' setting for Rage AutoStrafer that will make strafes invisible both client and server-side

Implement silent Rage AutoStrafer

---

src/Hacks/esp.cpp
src/Hacks/esp.h
src/Hooks/BeginFrame.cpp
src/Hooks/DrawModelExecute.cpp

The reason for this is glow internally calls ForcedMaterialOverride()
which should be called in DrawModelExecute().
[https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/client/glow_outline_effect.cpp#L161-L162](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/client/glow_outline_effect.cpp#L161-L162)

Fix glow esp flickering

---

load

`set -e` exits immediately upon any non-zero return, which blocks some functions of our load script. This line adds no additional functionality to the script and just causes issues.
As for changing `echo` to `/bin/echo`, some terminals execute with Dash instead of Bash. See [here](http://askubuntu.com/a/434167) for explanation.

Remove set -e, change echo to /bin/echo

---

src/Hacks/esp.cpp
src/Hacks/hitmarkers.cpp
src/Hacks/namechanger.cpp
src/Hacks/namechanger.h
src/Utils/netvarmanager.cpp
src/atgui.cpp
src/interfaces.cpp

* ESP::DrawPlantedBomb() used 24-23 bytes per bomb tick
* Hitmarkers::Paint() used a few bytes per hit
* NameChanger::GetName() used a bunch of bytes each call
* NetVarManager::dumpNetvars() used a bunch of bytes once
* AimbotTab() used a bunch of bytes each call
* PlayerListWindow() used a few bytes each call
* Interfaces::dumpInterfaces() used a bunch of bytes once
asprintf(3):
> DESCRIPTION
>        The  functions asprintf() and vasprintf() are analogs of sprintf(3) and
>        vsprintf(3), except that they allocate a string large  enough  to  hold
>        the  output  including  the  terminating null byte ('\0'), and return a
>        pointer to it via the first argument.  **This pointer should be passed to
>        free(3) to release the allocated storage when it is no longer …

Fix a bunch of memory leaks

---

src/AimTux.cpp
src/Hacks/skinchanger.cpp
src/Hacks/skinchanger.h
src/Utils/recvproxyhook.h
src/hooker.cpp
src/hooker.h

Should make any future hooking of NetVar proxy functions a lot easier. The `HookRecvProp` function in the hooker file doesn't recurse child tables yet - I'm not really sure how to do it with the NetVar manager that AimTux uses. Most code was adapted from [Chameleon NG](https://github.com/emskye96/chameleon-ng/blob/master/src/Chameleon.cpp#L79-L85).
I wasn't really sure where to put everything so maybe some things will need moving around or cleaning up.

Use generic RecvPropHook class for m_nSequence hook.

---

pkg/PKGBUILD

You have to manually initialize the submodules in the PKGBUILD

Missing submodule ImGUI in PKGBUILD

---

src/Hacks/autostrafe.cpp

Setting forward/side move to any value over 450.f will get you untrusted.

Small untrusted fix

---

src/Hacks/hacks.h
src/Hacks/jumpthrow.cpp
src/Hacks/jumpthrow.h
src/Hooks/CreateMove.cpp
src/atgui.cpp
src/settings.cpp
src/settings.h

This basically allows the user to set a custom key and enable/disable a feature that executes a perfect jump throw. This is good for map smokes. There's already console binds for this online, but I thought that it would be convenient to have it built into the misc. tab anyways. Besides, this adds more functionality to it:
- It checks if the user is holding a grenade or not.
- Allows for easy custom keybinding
- Quick toggling via GUI
***Note***:
@McSwaggens I think I fixed all of the code style issues.

Implemented JumpThrow

---

src/Hacks/asuswalls.cpp
src/Hacks/noflash.cpp
src/Hacks/nosky.cpp
src/Hacks/view.cpp

Most of the visual hacks check if the Visual category is on before they work. However some do not.
This is useful because you can turn off all of the visual hacks at once by disabling the visual category.

Some visual hacks not checking if the Visual Category was enabled

---

src/Hacks/fakelag.cpp
src/atgui.cpp
src/settings.cpp
src/settings.h

Also disabled fakelag when onground because you would have to be choking 17 packets for it to break lag compensation when running with the knife and changed the default value to 9.

Adaptive FakeLag

---

src/Utils/util_items.cpp

Caused a crash when the weapon name was tried to be accessed and wasn't in the map.

Fixed bug with regard to custom weapons in some game modes.

---

rload
update

grep should be given the filename directly instead of using cat to pass the file contents.
Using cat is just a waste of performance!

Pass path into grep instead of using cat

---

.clang-format

Added a .clang-format file with the specifications for AimTux coding style. 
This should make the code look a lot cleaner along with giving a truly universal formatting style for AimTux.
It also allows other users to use their own .clang-formats while they're coding then change back to the AimTux clang.
I plan on mass formatting the existing code after this gets reviewed. Those folders are as follows:
src/Hacks/*
src/ATGUI/*
But exclude any files in the root of src/ for the sake of having it already well formatted. Also, no SDK, tools, or ImGUI should be formatted. 
I can write a script to apply the discriminant formatting for all to use if approved.

Added .clang-format file
