AimTuxOfficial/AimTux

README.md

Installed from the latest Ubuntu, Fedora and Arch ISOs in virtual machines with default settings and downloaded only the necessary packages to compile.
http://imgur.com/a/9j7WA

Update compilation instructions.

---

.lvimrc

Switch to a local rc plugin that works with nvim (embear/vim-localvimrc)

---

src/PANELS/aimbot_panel.cpp
src/PANELS/aimbot_panel.h
src/aimbot.cpp
src/settings.cpp
src/settings.h

Take two, see #37 for original and methodology.

Add an error margin to aimbot 

---

CMakeLists.txt

* -static-libstdc++ is a gcc-ish flag
* Use proper linker flag

Switch to CMAKE_SHARED_LINKER_FLAGS

---

README.md
src/AimTux.cpp
src/Hooks/RenderView.cpp
src/Hooks/hooks.h
src/PANELS/misc_panel.cpp
src/PANELS/misc_panel.h
src/SDK/CViewRender.h
src/SDK/SDK.h
src/SDK/definitions.h
src/fovchanger.cpp
src/fovchanger.h
src/hooker.cpp
src/hooker.h
src/interfaces.h
src/settings.cpp
src/settings.h

Add normal and viewmodel FOV changer.

---

src/SDK/IGameMovement.h
src/hooker.cpp
src/hooker.h
src/interfaces.h
src/predictionsystem.cpp

Use global move data pointer and fix incorrect SetHost virtual index.

---

src/PANELS/visuals_panel.cpp
src/PANELS/visuals_panel.h
src/esp.cpp
src/settings.cpp
src/settings.h

This fork no longer fails to inject also, so upload files from web browser to github was causing the issue.
As far as I can tell... fully functional.
Edit the colors from the config .json in the CSGO directory.

Added toggle to show friendly ESP. Also added name / hp colors.

---

src/settings.cpp
src/util.cpp
src/util.h
src/util_input.cpp
src/util_input.h
src/util_items.cpp
src/util_items.h

Add symbolic item names

---

src/PANELS/aimbot_panel.cpp
src/PANELS/aimbot_panel.h
src/PANELS/hvh_panel.cpp
src/PANELS/hvh_panel.h
src/PANELS/misc_panel.cpp
src/PANELS/triggerbot_panel.cpp
src/PANELS/visuals_panel.cpp
src/PANELS/visuals_panel.h
src/UI/toggle.h
src/UI/ui_container.cpp
src/UI/window.cpp
src/WINDOWS/main_window.cpp
src/atgui.cpp
src/chams.cpp
src/settings.cpp
src/settings.h

Changed almost everything size wise. Captilized toggles etc etc etc.

Updated UI. Made cleaner.

---

src/aimbot.cpp

Goes in a straight line to the head rather than moving uniformly in both directions.

Better smoothing function for aimbot

---

src/PANELS/aimbot_panel.cpp

Fix typo with new changes to smoothing

---

README.md

A missing colon

---

src/PANELS/misc_panel.cpp

Added "Airstuck Key" prefix to the key selector

Added "Airstuck Key" prefix to the key selector

---

src/chams.cpp

All of those std::endls are unnecessary, you only need one flush.

Removed unnecessary stream operators and std::endls

---

src/skinchanger.cpp

Probably not the best way of doing it but it does fix #192.

Fix knife skins by setting appropriate model to weapon.

---

src/settings.cpp

Fixed players_ally_visible_color not loading

---

README.md

updated readme.me

---

src/atgui.cpp

This way we can also get rid of the spectators window and make it plain text like it was before.

Added AimTux banner

---

src/atgui.cpp
src/esp.cpp
src/esp.h
src/settings.cpp
src/settings.h

Added health bar to ESP

---

src/atgui.cpp
src/esp.cpp
src/settings.cpp
src/settings.h

also removed health bar scaling because it looks wack

Added vertical health bars

---

src/esp.cpp

Fixed health bar going out of bounds

---

src/atgui.cpp
src/hooker.cpp
src/hooker.h

Returns a pointer to the actual `C_CSPlayerResource` which changes every time you join a server.

Find C_CSPlayerResource via signature scanning.

---

src/SDK/IClientEntity.h
src/atgui.cpp
src/offsets.cpp
src/offsets.h
src/settings.cpp
src/settings.h
src/spammer.cpp

It used to crash when adding messages to normal spammer because of the `static char* spammerMessageBuf`

Added money to spammer and fixed stuff

---

src/draw.cpp
src/draw.h
src/esp.cpp
src/esp.h

Added footstep ESP circles

---

src/recoilcrosshair.cpp

Fix recoil crosshair

---

src/esp.cpp

Fixed Flat 2D ESP box

---

CMakeLists.txt
README.md
src/aimbot.cpp
src/aimbot.h
src/atgui.cpp
src/settings.cpp
src/settings.h

Aiming is done by libxdo that simulates mouse movement.
If someone has changed their system's mouse sensitivity, the highlighted variable needs to be changed.
- Updated Cmakelist with the new library
- Updated the Readme with the new install instructions
- Added checkbox setting to Aimbot -> Others 
**Still needs testing on multiple environments**
Re: #330 #327

Experimental FaceIT support

---

src/SDK/IClientEntity.h
src/esp.cpp
src/esp.h

- There's no such thing as C_BasePlantedC4, no class inherits from C_PlantedC4

Rename C_BasePlantedC4 to C_PlantedC4

---

src/Hooks/BeginFrame.cpp
src/SDK/vector.h
src/atgui.cpp
src/radar.cpp
src/radar.h
src/settings.cpp
src/settings.h

- Remove old bSpotted radar
- Implement custom radar drawing using ImGui
- Add radar settings entries
- Add menu entries accordingly

Implement custom radar

---

src/atgui.cpp
src/radar.cpp
src/settings.cpp
src/settings.h

- Allow more precise zooming by using float instead of int
- Fine-tune radar drawing

Improve radar

---

src/SDK/IClientEntity.h
src/atgui.cpp
src/esp.cpp
src/esp.h
src/offsets.cpp
src/offsets.h
src/settings.cpp
src/settings.h

Implemented hitmarker

---

src/Hooks/FireEventClientSide.cpp
src/Hooks/Paint.cpp
src/atgui.cpp
src/esp.cpp
src/esp.h
src/hacks.h
src/hitmarkers.cpp
src/hitmarkers.h
src/settings.cpp
src/settings.h

- Add filters to hitmarkers
- Make size & gap customizable
- Make hitmarkers separate entry in the menu
- Use game events instead of netvars
- Move hitmarkers code to separate files

Fix & improve hitmarkers

---

src/antiaim.cpp
src/atgui.cpp
src/settings.h

c&p'd from UC, despite being memes some people may find these anti-aims useful
if this gets closed i can create a new pull request with all code-style fixes found here but without new anti-aims

Pasted anti-aim memes

---

src/Hacks/fovchanger.cpp

I shouldn't have made pull requests that late at night...

Fix Ignore Scope (#392)

---

src/offsets.h

"std::ptrdiff_t is used for pointer arithmetic" [(cppreference.com)](http://en.cppreference.com/w/cpp/types/ptrdiff_t)
its cool imo

Fix code style in offsets.h

---

src/Hacks/aimbot.cpp
src/Hacks/dlights.cpp
src/Hacks/esp.cpp
src/Hacks/radar.cpp
src/Hacks/triggerbot.cpp
src/Utils/entity.cpp
src/Utils/entity.h
src/atgui.cpp
src/settings.cpp
src/settings.h

- Add smoke-check for Aimbot, Triggerbot, ESP and Radar

Add smoke-checks

---

src/Hacks/antiaim.cpp
src/atgui.cpp
src/settings.h

I removed zero out in X & Y and I removed angel fake spin in Y Also fixed LISP.

AA Changes

---

src/SDK/IClientEntity.h

Changed m_bPinPulled to m_bIsHeldByPlayer for getting the corresponding bool

Wrong Offset used

---

src/settings.cpp

This removes the need to choose a specific function for every type when adding a variable to the config

Simplify config loading code

---

src/atgui.cpp

Having "HvH" at the top and "HvH Untrusted" at the bottom is completely unacceptable.

I fixed your hack (sort the config list)

---

src/Hacks/antiaim.cpp
src/SDK/vector.h

Improve spin type anti-aims

---

src/Hacks/aimbot.cpp
src/atgui.cpp
src/settings.cpp
src/settings.h

Still needs to be in sync with fov circle though

Implement real distance FOV

---

src/Hacks/esp.cpp

I've mistaken NormalizeAngles for ClampAngles for some reason

Fix real distance FOV circle

---

src/AimTux.cpp
src/Hacks/hitmarkers.cpp
src/Hacks/hitmarkers.h
src/Hooks/FireEvent.cpp
src/Hooks/FireEventClientSide.cpp
src/Hooks/hooks.h

player_hurt doesn't show up in FireEventClientSide in some instances

Fix hitmarkers

---

src/atgui.cpp

Just added 3 tooltips for existing options without tooltips in the ImGui menu.

Screenshot cleaner tooltip, show rank tooltip, auto defuse tooltip.

---

src/AimTux.cpp
src/EventListener.h
src/Hacks/hitmarkers.cpp
src/Hacks/hitmarkers.h
src/Hooks/FireEvent.cpp
src/SDK/IGameEvent.h

This (hopefully) fixes the hitmarker issue.
Tested on competitive (online and bots) and a few other gamemodes.

Add EventListener and use for hitmarkers

---

src/Hacks/namechanger.cpp
src/Hacks/namechanger.h
src/atgui.cpp

It colors your own name instead of "AIMTUX.NET".

Improve nickname color changing

---

.github/ISSUE_TEMPLATE.md
load
pkg/PKGBUILD
update

Signed-off-by: mpmjcvuut <mpmjcvuut@protonmail.ch>

Changed some stuff to reflect the new URL

---

README.md

Replaced two brief lines on code style requirements with a link to the code style wiki page. It goes more in-depth on the correct formatting of code to be contributed.

Added link to wiki on code style

---

src/Hacks/autowall.cpp

Since data.current_damage and data.trace_length is a float, we need to pow it with float-type function.

Replace pow with powf in autowall.cpp

---

load

So everything after the output isn't colored

Fix load script output

---

load

Add set -e
Use -z to check if the csgo pid is empty
Re-use the csgo_pid variable

Update load script

---

src/Hacks/esp.cpp
src/Hacks/esp.h
src/atgui.cpp
src/settings.cpp
src/settings.h

Hope I've done everything right...
Pretty much just draws a dot at the head bone

Add Headdot Feature

---

src/AimTux.cpp
src/Hacks/hacks.h
src/Hacks/snipercrosshair.cpp
src/Hacks/snipercrosshair.h
src/Hooks/BeginFrame.cpp
src/atgui.cpp
src/hooker.cpp
src/hooker.h
src/interfaces.h
src/settings.cpp
src/settings.h

This change byte-patches the weapon-type check in C_WeaponCSBase::DrawCrosshair()
Criticism and suggestions are welcome.
Edit (added image):

Add Sniper Crosshair

---

src/Utils/patternfinder.cpp
src/Utils/patternfinder.h
src/hooker.cpp
src/hooker.h

Use modules' memory size for sigscanning

---

update

This is only so the user can keep on going without any extra work needed.

Fixes itself so the user doesn't have to.

---

update

Add recursive flag to error message instructions.

---

src/Hacks/aimbot.cpp
src/Hacks/triggerbot.cpp
src/atgui.cpp
src/settings.cpp
src/settings.h

Implement flash check on aimbot and triggerbot

---

src/Hacks/aimbot.cpp
src/Hacks/aimbot.h
src/atgui.cpp
src/settings.cpp
src/settings.h

it now dynamically slows you down to your weapons crouch speed so that you have maximum accuracy rather than two arbitrary values

Better AutoSlow

---

src/Hacks/nosmoke.cpp

Works fine with just these four.

Remove useless materials from nosmoke.cpp

---

src/Hacks/aimbot.cpp
src/atgui.cpp
src/settings.cpp
src/settings.h

Added a simple velocity prediction and fixed one of the variable names because it's not always the head (p body aim)

Velocity Prediction + Fix Variable Name

---

src/Hacks/antiaim.cpp
src/atgui.cpp
src/settings.cpp
src/settings.h

Added Anti Resolver

---

src/Hacks/antiaim.cpp
src/atgui.cpp
src/settings.h

(Hope I didnt fuck up this time)
Just some small aa's. They're on the untrusted list for now, because they haven't been tested for as long as i'd like them to be. Could move them when they get tested more.
(In a few hours if I still get no untrusted in a server with untrusted plugin i will make another to remove it from the untrusted list)

New AA's - @WeAreSoGBoosting - 

---

src/hooker.h

Fixed the sig for the valetines update because I love you all

Fixed sig for Valetines update

---

LICENSE

I doubt that the project will ever actually need this change, but it is good to be on the latest license for updated terminology and compatibility. See [Why Upgrade to GPLv3](https://www.gnu.org/licenses/rms-why-gplv3.en.html) & [What are the differences between GPL v2 and GPL v3 licenses?](http://stackoverflow.com/a/44701).

Updated license to GPL 3.0

---

src/ATGUI/Tabs/misctab.cpp
src/AimTux.cpp
src/Hacks/disablepostprocessing.cpp
src/Hacks/disablepostprocessing.h
src/Hacks/hacks.h
src/Hooks/BeginFrame.cpp
src/hooker.cpp
src/hooker.h
src/interfaces.h
src/settings.cpp
src/settings.h

This change disables post-processing by setting the s_bOverridePostProcessingDisable
variable to true.

Add option to disable post processing

---

src/SDK/CCSGameRules.h

Added a small function to check if it is the FreezeTime ( Buy time ).
It can be called like so 
`(*csGameRules)->IsFreezeTime()`

Added Freezetime Check Method

---

src/ATGUI/Tabs/misctab.cpp
src/Hacks/grenadehelper.cpp

this is just a small fix
this fixes https://www.youtube.com/watch?v=DfjVxv-QS4c

Small fixes for Grenadehelper

---

src/SDK/IClientEntity.h

https://paste.ubuntu.com/24244876/

Update CCSWeaponInfo offsets
